services:
  - type: web
    name: krishibazaar
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn krishibazaar.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        value: postgresql://krishi_bazar_user:uja1zCHXoPsJ27l2y8WQPUiEt0IPpKdM@dpg-d2upr60gjchc73aivc90-a.singapore-postgres.render.com/krishi_bazar