services:
  - type: web
    name: krishi-bazaar
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt && \
      python manage.py collectstatic --noinput && \
      python manage.py migrate --noinput
    startCommand: gunicorn krishibazaar.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      # Prefer runtime.txt, but this ensures Python version on Render
      - key: PYTHON_VERSION
        value: 3.12.6
      # Set the following in the Render dashboard or via Render Postgres add-on
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: your-postgres
      #     property: connectionString
      # - key: SECRET_KEY
      #   sync: false
      # - key: DEBUG
      #   value: "False"
      # - key: ALLOWED_HOSTS
      #   value: krishi-bazaar-fmst.onrender.com

