services:
  # Web service
  - type: web
    name: krishibazaar-web
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn krishibazaar.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: krishibazaar.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: krishi-bazaar-qj7z.onrender.com,krishi-bazar-za8m.onrender.com,krishi-bazar-2.onrender.com,*.onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        value: postgresql://krishi_bazar_0nd1_user:z2lmmRte3MNn1wcDwFu5DqKmdmLHwDvU@dpg-d3388jripnbc73dongn0-a.oregon-postgres.render.com/krishi_bazar_0nd1
      - key: STATIC_URL
        value: /static/
      - key: MEDIA_URL
        value: /media/
      - key: STATIC_ROOT
        value: staticfiles
      - key: MEDIA_ROOT
        value: media
    healthCheckPath: /
    disk:
      name: krishibazaar-disk
      mountPath: /opt/render/project/src/media
      sizeGB: 1

