services:
  # Web service
  - type: web
    name: krishibazaar-web
    env: python
    plan: starter
    buildCommand: pip install -r requirements-prod.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn krishibazaar.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: krishibazaar.settings_production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: krishibazaar.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: krishibazaar-db
          property: connectionString
      - key: STATIC_URL
        value: /static/
      - key: MEDIA_URL
        value: /media/
      - key: STATIC_ROOT
        value: staticfiles
      - key: MEDIA_ROOT
        value: media
    healthCheckPath: /
    disk:
      name: krishibazaar-disk
      mountPath: /opt/render/project/src/media
      sizeGB: 1

  # Database service
  - type: pserv
    name: krishibazaar-db
    env: postgresql
    plan: starter
    disk:
      name: krishibazaar-db-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
