# Generated by Django 5.2 on 2025-04-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='page_scope',
            field=models.CharField(choices=[('global', 'Global'), ('crops', 'Crops Page'), ('bids', 'Bids Page'), ('demands', 'Demands Page')], default='global', max_length=20, verbose_name='Page Scope'),
        ),
    ]
