# Generated by Django 5.2 on 2025-04-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_page_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='page_scope',
        ),
    ]
